import { describe, expect, it } from "vitest";
import { classifyRole, createRoleClassifier } from "./roles.js";

describe("classifyRole", () => {
  it.each([
    [".prettierrc.js", "javascript"],
    ["tools/prettierrc.js", "javascript"],
    ["common/config/rush/command-line.json", "json"],
    ["fixtures/payload.json", "json"],
    [".cursor/rules/project.mdc", "other"],
    ["packages/app/.cursor/settings.json", "json"],
    ["build.sh", "shell"],
    ["apps/api/build.sh", "shell"],
  ] as const)("把 %s 归为默认隐藏的配置噪音", (path, language) => {
    expect(classifyRole(path, language)).toBe("config");
  });

  it("不把普通 shell 脚本或名字像配置的源码一并隐藏", () => {
    expect(classifyRole("scripts/deploy.sh", "shell")).toBe("source");
    expect(classifyRole("src/config.ts", "typescript")).toBe("source");
    expect(classifyRole("examples/client.ts", "typescript")).toBe("source");
    expect(classifyRole("tools/migrate.py", "python")).toBe("source");
  });

  it("测试和生成目录仍优先于通用 JSON 规则", () => {
    expect(classifyRole("src/data.test.json", "json")).toBe("test");
    expect(classifyRole("dist/manifest.json", "json")).toBe("generated");
  });

  it.each([
    ["vendor/library.js", "javascript", "vendor"],
    ["third-party/sdk/client.py", "python", "vendor"],
    [".yarn/cache/pkg/index.js", "javascript", "vendor"],
    ["src/__fixtures__/payload.ts", "typescript", "test"],
    ["src/view.stories.tsx", "tsx", "test"],
    ["src/api.gen.ts", "typescript", "generated"],
    ["src/model.designer.js", "javascript", "generated"],
    [".vscode/settings.json", "json", "config"],
    [".devcontainer/devcontainer.json", "json", "config"],
    ["README", "other", "docs"],
    ["docs-site/README.md", "markdown", "docs"],
    ["src/types.pyi", "python", "types"],
  ] as const)("按生态约定将 %s 识别为 %s", (path, language, role) => {
    expect(classifyRole(path, language)).toBe(role);
  });

  it.each([
    ["src/api.go", "go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api"],
    ["src/schema.ts", "typescript", "// <auto-generated />\nexport const schema = {};"],
    ["src/client.py", "python", "# This file was automatically generated\nclass Client: pass"],
    ["src/model.rs", "rust", "// @generated\npub struct Model {}"],
  ] as const)("根据文件头将 %s 识别为 generated", (path, language, source) => {
    expect(classifyRole(path, language, source)).toBe("generated");
  });

  it("生成标记只检查文件开头，业务正文中的同名字符串不会误伤", () => {
    const source = `${"export const x = 1;\n".repeat(45)}export const notice = "@generated";`;
    expect(classifyRole("src/manual.ts", "typescript", source)).toBe("source");
    expect(classifyRole("src/manual.ts", "typescript", 'export const notice = "@generated";'))
      .toBe("source");
  });

  it("路径角色优先于内容标记", () => {
    expect(classifyRole("src/api.test.ts", "typescript", "// @generated")).toBe("test");
  });

  it("允许项目把内置噪音规则显式覆盖为源码，后写的规则优先", () => {
    const classify = createRoleClassifier({
      "**/*.json": "config",
      "runtime/**/*.json": "source",
    });
    expect(classify("runtime/workflow.json", "json")).toBe("source");
    expect(classify("config/settings.json", "json")).toBe("config");
  });
});
